version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: git push heroku master
workflows:
  node-tests:
    jobs:
      - node/test
      - build
